# Generated by Django 5.2.8 on 2025-11-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
