# Generated by Django 5.2.8 on 2025-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_cats', models.IntegerField(default=0)),
                ('new_cats', models.IntegerField(default=0)),
            ],
        ),
    ]
