# Generated by Django 5.2.8 on 2025-12-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_updatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updatelog',
            name='adopted_cats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cat',
            name='first_seen',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cat',
            name='last_seen',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
