# Generated by Django 5.2.8 on 2025-12-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_adopted_updatelog_adopted_cats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('adopted', 'Adopted'), ('pending', 'Pending'), ('new', 'New')], default='available', max_length=20),
        ),
    ]
