# Generated by Django 5.2.8 on 2025-12-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_cat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='adopted',
        ),
    ]
