# Generated by Django 5.2.8 on 2025-12-29 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_remove_cat_adopted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='birthday',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='cat',
            name='intake_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='location',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='cat',
            name='primary_color',
            field=models.CharField(default='Unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='cat',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
