# Generated by Django 5.2.8 on 2026-01-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_cat_birthday_cat_breed_cat_intake_date_cat_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats/'),
        ),
    ]
